import Head from 'next/head'
import Link from 'next/link'
import menu from '@/menu';
import { Inter } from 'next/font/google'


export default function Home() {
	return (
		<>
		<Head>
			<title>Advanced Typescript</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<main>
			<div className="container mx-auto mt-10">
				<div className="py-2 px-4">
					<h2 className="text-left text-2xl text-gray-800 mb-2">Advance Typescript</h2>
					<ul className="list-none">
						{
							menu.map((menu, idx) => {
								return (
								<li key={idx} className="py-1">
									<Link className="text-blue-500 hover hover:text-blue-700 transition duration-150" href={menu.href}>{menu.label}</Link>
								</li>
								)
							})
						}
					</ul>
				</div>
			</div>
		</main>
		</>
	)
}
